// SPDX-License-Identifier: MS-PL
/**
 * @file CppProjectExport.cpp
 * @brief Writes the files that make a directory a buildable CNA C++ project.
 *
 * Two callers: `--export`, which writes a copy of the project somewhere else, and the Project Hub,
 * which writes them into a project it is creating. One set of generators, because an export and a
 * new project that drift are two things only one of which has a build test.
 */

#include "CNA/Studio/Project/Cpp/CppProjectExport.hpp"

#include "CNA/Studio/Project/Cpp/CppRuntimeSources.hpp"
#include "CNA/Studio/Project/Cpp/CppToolchain.hpp"
#include "CNA/Studio/Project/Project.hpp"
#include "CNA/Studio/Project/TargetProfile.hpp"

#include <cctype>
#include <filesystem>
#include <fstream>
#include <system_error>

namespace CNA::Studio
{
    namespace
    {
        /**
         * @brief Writes @p contents to @p path, creating parent directories.
         *
         * @param path Absolute destination.
         * @param contents Bytes to write.
         * @param errorMessage Filled in on failure.
         * @return Whether the file was written.
         */
        bool writeFile(const std::filesystem::path& path,
                       std::string_view contents,
                       std::string& errorMessage)
        {
            std::error_code code;
            std::filesystem::create_directories(path.parent_path(), code);
            if (code)
            {
                errorMessage = "cannot create '" + path.parent_path().generic_string()
                             + "': " + code.message();
                return false;
            }

            // Binary, deliberately. A source file written in text mode on Windows gets CRLF line
            // endings it did not have in Studio's tree, which is a diff nobody made and, for the
            // embedded runtime, a file that no longer matches the one it was embedded from.
            std::ofstream stream{path, std::ios::binary | std::ios::trunc};
            if (!stream)
            {
                errorMessage = "cannot write '" + path.generic_string() + "'";
                return false;
            }

            stream.write(contents.data(), static_cast<std::streamsize>(contents.size()));
            if (!stream)
            {
                errorMessage = "failed while writing '" + path.generic_string() + "'";
                return false;
            }
            return true;
        }

        /** @brief The CMake source-file list for whatever of the runtime must be compiled. */
        std::string runtimeCompiledSourceList()
        {
            std::string list;
            for (const StudioRuntimeSource& source : studioRuntimeSources())
            {
                if (!source.compiled) { continue; }
                list += "    " + std::string{source.pathInProject} + "\n";
            }
            return list;
        }

        /**
         * @brief The exported project's own CMakeLists.txt.
         *
         * It asks for exactly one thing the machine must already have: a CNA source checkout. CNA
         * installs no package configuration and exports no targets, so `find_package(CNA)` is not
         * available to write -- `add_subdirectory` on a checkout is the only way anything consumes
         * CNA today. Recorded as a CNA gap (G-09) rather than worked around silently, and the
         * generated file says so where the person who has to supply the path will read it.
         */
        /** @brief One directory the build copies beside the executable. */
        struct ContentStaging
        {
            /** @brief Project-relative source directory. */
            std::string from;
            /** @brief Destination, relative to the directory the executable lands in. */
            std::string to;
        };

        std::string cmakeListsFor(const std::string& targetName,
                                  const StudioTargetProfile& profile,
                                  const std::vector<ContentStaging>& staging,
                                  ProjectKind kind)
        {
            std::string text;
            text += "# Generated by CNA Studio. This is an ordinary CNA project: it needs CMake, a\n";
            text += "# C++23 compiler and a CNA checkout, and nothing else. CNA Studio does not have\n";
            text += "# to be installed to build or run this game, and nothing here refers to it.\n";
            text += "#\n";
            text += "# Edit it freely. Studio will not rewrite this file behind you -- re-exporting\n";
            text += "# into a directory that already has one requires asking for it explicitly.\n";
            text += "cmake_minimum_required(VERSION 3.20)\n";
            text += "project(" + targetName + " LANGUAGES CXX)\n\n";
            text += "set(CMAKE_CXX_STANDARD 23)\n";
            text += "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n\n";
            text += "# Where CNA is. Pass -DCNA_ROOT=/path/to/cna, or set it in the environment.\n";
            text += "# CNA ships no installed package configuration and exports no targets, so\n";
            text += "# add_subdirectory on a source checkout is how everything consumes it today --\n";
            text += "# including CNA Studio itself. When CNA gains a find_package(CNA), this becomes\n";
            text += "# two lines shorter and stops needing a path at all.\n";
            text += "if(NOT CNA_ROOT AND DEFINED ENV{CNA_ROOT})\n";
            text += "    set(CNA_ROOT \"$ENV{CNA_ROOT}\")\n";
            text += "endif()\n";
            text += "if(NOT CNA_ROOT)\n";
            text += "    message(FATAL_ERROR\n";
            text += "        \"CNA_ROOT is not set. Point it at a CNA checkout:\\n\"\n";
            text += "        \"  cmake -S . -B build -DCNA_ROOT=/path/to/cna\")\n";
            text += "endif()\n";
            text += "if(NOT EXISTS \"${CNA_ROOT}/CMakeLists.txt\")\n";
            text += "    message(FATAL_ERROR \"CNA_ROOT='${CNA_ROOT}' is not a CNA checkout.\")\n";
            text += "endif()\n\n";
            text += "# How this project was authored to build. Every one of these is an ordinary\n";
            text += "# CNA configure option, and every one is overridable on the command line: a\n";
            text += "# game builds for whatever its builder selects, not for whatever the machine\n";
            text += "# that exported it happened to have. They are written as cache entries rather\n";
            text += "# than plain variables for exactly that reason.\n";
            for (const std::string& argument : studioTargetProfileCMakeArguments(profile))
            {
                // -DNAME=VALUE, as the build runner would pass it. Rendered here as the cache
                // entry that means the same thing, so the exported build and the one Studio runs
                // configure CNA identically -- and so a feature added to the profile model appears
                // in exported projects without anybody remembering to add it here too.
                const std::size_t equals = argument.find('=');
                if (equals == std::string::npos || argument.rfind("-D", 0) != 0) { continue; }

                const std::string name = argument.substr(2, equals - 2);
                const std::string value = argument.substr(equals + 1);
                if (name == "CMAKE_BUILD_TYPE")
                {
                    // Guarded: a multi-configuration generator picks the configuration at build
                    // time, and forcing this there is how a Debug build silently comes out Release.
                    text += "if(NOT CMAKE_CONFIGURATION_TYPES AND NOT CMAKE_BUILD_TYPE)\n";
                    text += "    set(CMAKE_BUILD_TYPE \"" + value + "\" CACHE STRING \"Build configuration\")\n";
                    text += "endif()\n";
                    continue;
                }
                text += "set(" + name + " \"" + value + "\" CACHE STRING \"Set by CNA Studio's export\")\n";
            }
            text += "\n";
            text += "# CNA builds its own test suite and its example programs by default, even when\n";
            text += "# it is consumed as a subdirectory rather than built on its own: neither option\n";
            text += "# is guarded by a top-level-project check. A game that only wants to *use* CNA\n";
            text += "# would compile the engine's whole test suite and every demo into its own build.\n";
            text += "#\n";
            text += "# Worse than slow: on a checkout without initialised submodules the tests fail\n";
            text += "# the configure outright looking for googletest, and CNA's examples resolve a\n";
            text += "# helper script through CMAKE_SOURCE_DIR -- which, from a subdirectory, is *this*\n";
            text += "# project's root, not CNA's -- so they cannot build from here at all.\n";
            text += "#\n";
            text += "# Cache entries, so you can turn either back on if you want them.\n";
            text += "set(CNA_BUILD_TESTS OFF CACHE BOOL \"Build CNA's own test suite\")\n";
            text += "set(CNA_BUILD_EXAMPLES OFF CACHE BOOL \"Build CNA's example programs\")\n\n";
            text += "add_subdirectory(\"${CNA_ROOT}\" \"${CMAKE_BINARY_DIR}/cna\")\n\n";
            // An XNA-compatible project has no scenes, so it is not given the scene runtime: a
            // game whose structure is its own would be compiling a loader for a format it never
            // reads, and a file it has no reason to keep is a file somebody has to wonder about.
            if (kind == ProjectKind::XnaCompatible)
            {
                text += "add_executable(" + targetName + " Source/Main.cpp)\n\n";
                text += "target_link_libraries(" + targetName + " PRIVATE CNA)\n\n";
            }
            else
            {
                text += "# The scene runtime, compiled as part of the game. It is project-owned source,\n";
                text += "# not a library the build machine is expected to have: see Runtime/README.md.\n";
                text += "add_executable(" + targetName + "\n";
                text += "    Source/Main.cpp\n";
                text += runtimeCompiledSourceList();
                text += ")\n\n";
                text += "target_include_directories(" + targetName + " PRIVATE Runtime/include)\n";
                text += "target_link_libraries(" + targetName + " PRIVATE CNA)\n\n";
            }
            text += "# Content sits beside the executable so the game finds it with a relative path\n";
            text += "# whatever directory it is launched from.\n";
            text += "add_custom_command(TARGET " + targetName + " POST_BUILD\n";
            for (const ContentStaging& directory : staging)
            {
                text += "    COMMAND \"${CMAKE_COMMAND}\" -E copy_directory\n";
                text += "            \"${CMAKE_CURRENT_SOURCE_DIR}/" + directory.from + "\"\n";
                text += "            \"$<TARGET_FILE_DIR:" + targetName + ">/" + directory.to + "\"\n";
            }
            text += "    COMMENT \"Staging content beside the executable\")\n";
            return text;
        }

        /** @brief The game's `main`: load the startup scene, draw it, and be testable doing it. */
        std::string mainSourceFor(const std::string& targetName, const std::string& startupScene)
        {
            std::string text;
            text += "// Generated by CNA Studio as the starting point for " + targetName + ".\n";
            text += "//\n";
            text += "// This is your game's entry point, not a generated file to leave alone: the\n";
            text += "// export writes it once and never touches it again. It loads the startup\n";
            text += "// scene through the project-owned runtime in Runtime/, draws it, and accepts\n";
            text += "// the arguments an automated smoke test needs. Replace the body with your\n";
            text += "// game; keep the loader call.\n";
            text += "//\n";
            text += "// Nothing here refers to CNA Studio. That is the point: this project builds\n";
            text += "// and ships on a machine that has never had Studio installed.\n";
            text += "\n";
            text += "#include <cstdlib>\n";
            text += "#include <exception>\n";
            text += "#include <filesystem>\n";
            text += "#include <iostream>\n";
            text += "#include <memory>\n";
            text += "#include <string>\n";
            text += "\n";
            text += "#include \"Microsoft/Xna/Framework/Game.hpp\"\n";
            text += "#include \"Microsoft/Xna/Framework/GraphicsDeviceManager.hpp\"\n";
            text += "#include \"Microsoft/Xna/Framework/Graphics/BlendState.hpp\"\n";
            text += "#include \"Microsoft/Xna/Framework/Graphics/SpriteBatch.hpp\"\n";
            text += "#include \"Microsoft/Xna/Framework/Graphics/SpriteSortMode.hpp\"\n";
            text += "\n";
            text += "#include \"CNA/Studio/Runtime/SceneLoader.hpp\"\n";
            text += "\n";
            text += "namespace Xna = Microsoft::Xna::Framework;\n";
            text += "namespace XnaGraphics = Microsoft::Xna::Framework::Graphics;\n";
            text += "namespace Runtime = CNA::Studio::Runtime;\n";
            text += "\n";
            text += "namespace\n";
            text += "{\n";
            text += "    /** @brief The startup scene, relative to the staged Content directory. */\n";
            text += "    const char* const kStartupScene = \"" + startupScene + "\";\n";
            text += "\n";
            text += "    class " + targetName + "Game final : public Xna::Game\n";
            text += "    {\n";
            text += "    public:\n";
            text += "        " + targetName + "Game(std::string contentRoot, int frameLimit)\n";
            text += "            : contentRoot_(std::move(contentRoot)), frameLimit_(frameLimit)\n";
            text += "        {\n";
            text += "            graphics_ = std::make_unique<Xna::GraphicsDeviceManager>(this);\n";
            text += "        }\n";
            text += "\n";
            text += "        [[nodiscard]] bool loaded() const { return loaded_; }\n";
            text += "        [[nodiscard]] std::size_t entityCount() const { return entities_; }\n";
            text += "        [[nodiscard]] std::size_t spritesDrawn() const { return spritesDrawn_; }\n";
            text += "\n";
            text += "    protected:\n";
            text += "        void LoadContent() override\n";
            text += "        {\n";
            text += "            spriteBatch_ =\n";
            text += "                std::make_unique<XnaGraphics::SpriteBatch>(getGraphicsDeviceProperty());\n";
            text += "\n";
            text += "            const std::filesystem::path content{contentRoot_};\n";
            text += "            Runtime::SceneLoadResult result = Runtime::loadScene(\n";
            text += "                (content / kStartupScene).generic_string(),\n";
            text += "                getGraphicsDeviceProperty(), content.generic_string());\n";
            text += "\n";
            text += "            for (const std::string& warning : result.warnings)\n";
            text += "            {\n";
            text += "                std::cerr << \"warning: \" << warning << \"\\n\";\n";
            text += "            }\n";
            text += "            if (!result.succeeded)\n";
            text += "            {\n";
            text += "                std::cerr << \"error: \" << result.errorMessage << \"\\n\";\n";
            text += "                Exit();\n";
            text += "                return;\n";
            text += "            }\n";
            text += "\n";
            text += "            scene_ = std::move(result.scene);\n";
            text += "            entities_ = scene_.getEntities().size();\n";
            text += "            loaded_ = true;\n";
            text += "        }\n";
            text += "\n";
            text += "        void Update(Xna::GameTime& gameTime) override\n";
            text += "        {\n";
            text += "            Game::Update(gameTime);\n";
            text += "            ++frames_;\n";
            text += "            if (frameLimit_ > 0 && frames_ >= frameLimit_) { Exit(); }\n";
            text += "        }\n";
            text += "\n";
            text += "        void Draw(const Xna::GameTime& gameTime) override\n";
            text += "        {\n";
            text += "            getGraphicsDeviceProperty().Clear(Xna::Color(30, 30, 40, 255));\n";
            text += "            if (loaded_)\n";
            text += "            {\n";
            text += "                // BackToFront is what makes the layer depth the editor showed\n";
            text += "                // you mean the same thing here.\n";
            text += "                spriteBatch_->Begin(XnaGraphics::SpriteSortMode::BackToFront,\n";
            text += "                                    XnaGraphics::BlendState::NonPremultiplied);\n";
            text += "                spritesDrawn_ = scene_.draw(*spriteBatch_);\n";
            text += "                spriteBatch_->End();\n";
            text += "            }\n";
            text += "            Game::Draw(gameTime);\n";
            text += "        }\n";
            text += "\n";
            text += "    private:\n";
            text += "        std::string contentRoot_;\n";
            text += "        int frameLimit_ = 0;\n";
            text += "        int frames_ = 0;\n";
            text += "        bool loaded_ = false;\n";
            text += "        std::size_t entities_ = 0;\n";
            text += "        std::size_t spritesDrawn_ = 0;\n";
            text += "\n";
            text += "        std::unique_ptr<Xna::GraphicsDeviceManager> graphics_;\n";
            text += "        std::unique_ptr<XnaGraphics::SpriteBatch> spriteBatch_;\n";
            text += "        Runtime::LoadedScene scene_;\n";
            text += "    };\n";
            text += "}\n";
            text += "\n";
            text += "int main(int argc, char** argv)\n";
            text += "{\n";
            text += "    // Content is staged beside the executable by the build, so the default is\n";
            text += "    // relative to the working directory and --content overrides it.\n";
            text += "    std::string contentRoot = \"Content\";\n";
            text += "    int frameLimit = 0;\n";
            text += "\n";
            text += "    for (int index = 1; index < argc; ++index)\n";
            text += "    {\n";
            text += "        const std::string argument{argv[index] != nullptr ? argv[index] : \"\"};\n";
            text += "        if (argument.rfind(\"--content=\", 0) == 0) { contentRoot = argument.substr(10); }\n";
            text += "        else if (argument.rfind(\"--frames=\", 0) == 0)\n";
            text += "        {\n";
            text += "            frameLimit = std::atoi(argument.substr(9).c_str());\n";
            text += "        }\n";
            text += "        else if (argument == \"--help\")\n";
            text += "        {\n";
            text += "            std::cout << \"" + targetName + " [--content=DIR] [--frames=N]\\n\";\n";
            text += "            return 0;\n";
            text += "        }\n";
            text += "    }\n";
            text += "\n";
            text += "    try\n";
            text += "    {\n";
            text += "        " + targetName + "Game game{contentRoot, frameLimit};\n";
            text += "        game.Run();\n";
            text += "\n";
            text += "        if (!game.loaded())\n";
            text += "        {\n";
            text += "            std::cerr << \"" + targetName + ": the startup scene did not load\\n\";\n";
            text += "            return 1;\n";
            text += "        }\n";
            text += "\n";
            text += "        // Printed rather than merely returned: a smoke test that can only read\n";
            text += "        // an exit code cannot tell a game that drew its scene from one that\n";
            text += "        // opened a window and drew nothing.\n";
            text += "        std::cout << \"" + targetName + ": loaded \" << game.entityCount()\n";
            text += "                  << \" entities, drew \" << game.spritesDrawn() << \" sprites\\n\";\n";
            text += "        return 0;\n";
            text += "    }\n";
            text += "    catch (const std::exception& error)\n";
            text += "    {\n";
            text += "        std::cerr << \"" + targetName + ": \" << error.what() << \"\\n\";\n";
            text += "        return 2;\n";
            text += "    }\n";
            text += "}\n";
            return text;
        }

        /**
         * @brief A hand-written CNA game's `main`: its own loop, and no entity model at all.
         *
         * `plan.md` STUDIO-08008. This is what the XNA-compatible project kind means in practice
         * (`docs/ARCHITECTURE.md` §8): the game keeps `Initialize`, `LoadContent`, `Update` and
         * `Draw`, and nothing Studio invented appears in it. A port coming from XNA must never be
         * pushed through an entity model to use the tooling, and a generated `main` that loaded a
         * scene would be exactly that push, applied on the first line of the project.
         */
        std::string xnaMainSourceFor(const std::string& targetName)
        {
            std::string text;
            text += "// Generated by CNA Studio as the starting point for " + targetName + ".\n";
            text += "//\n";
            text += "// This is an ordinary CNA game with its own structure: Initialize,\n";
            text += "// LoadContent, Update and Draw, exactly as XNA has them, and no scene, entity\n";
            text += "// or component model anywhere in it. CNA Studio offers this project the asset\n";
            text += "// browser, importer settings, content preview, renderer configuration and\n";
            text += "// Play -- and leaves everything else to you.\n";
            text += "//\n";
            text += "// The export writes this file once and never touches it again.\n";
            text += "\n";
            text += "#include <cstdlib>\n";
            text += "#include <exception>\n";
            text += "#include <iostream>\n";
            text += "#include <memory>\n";
            text += "#include <string>\n";
            text += "\n";
            text += "#include \"Microsoft/Xna/Framework/Game.hpp\"\n";
            text += "#include \"Microsoft/Xna/Framework/GraphicsDeviceManager.hpp\"\n";
            text += "#include \"Microsoft/Xna/Framework/Graphics/BlendState.hpp\"\n";
            text += "#include \"Microsoft/Xna/Framework/Graphics/SpriteBatch.hpp\"\n";
            text += "#include \"Microsoft/Xna/Framework/Graphics/SpriteSortMode.hpp\"\n";
            text += "\n";
            text += "namespace Xna = Microsoft::Xna::Framework;\n";
            text += "namespace XnaGraphics = Microsoft::Xna::Framework::Graphics;\n";
            text += "\n";
            text += "namespace\n";
            text += "{\n";
            text += "    class " + targetName + "Game final : public Xna::Game\n";
            text += "    {\n";
            text += "    public:\n";
            text += "        explicit " + targetName + "Game(int frameLimit) : frameLimit_(frameLimit)\n";
            text += "        {\n";
            text += "            graphics_ = std::make_unique<Xna::GraphicsDeviceManager>(this);\n";
            text += "        }\n";
            text += "\n";
            text += "        [[nodiscard]] int framesRun() const { return frames_; }\n";
            text += "\n";
            text += "    protected:\n";
            text += "        void Initialize() override\n";
            text += "        {\n";
            text += "            // Set up whatever does not need the graphics device here.\n";
            text += "            Game::Initialize();\n";
            text += "        }\n";
            text += "\n";
            text += "        void LoadContent() override\n";
            text += "        {\n";
            text += "            // Load your textures, fonts and sounds here. Content is staged\n";
            text += "            // beside the executable by the build.\n";
            text += "            spriteBatch_ =\n";
            text += "                std::make_unique<XnaGraphics::SpriteBatch>(getGraphicsDeviceProperty());\n";
            text += "        }\n";
            text += "\n";
            text += "        void Update(Xna::GameTime& gameTime) override\n";
            text += "        {\n";
            text += "            // Your game's logic goes here.\n";
            text += "            Game::Update(gameTime);\n";
            text += "            ++frames_;\n";
            text += "            if (frameLimit_ > 0 && frames_ >= frameLimit_) { Exit(); }\n";
            text += "        }\n";
            text += "\n";
            text += "        void Draw(const Xna::GameTime& gameTime) override\n";
            text += "        {\n";
            text += "            getGraphicsDeviceProperty().Clear(Xna::Color(100, 149, 237, 255));\n";
            text += "\n";
            text += "            spriteBatch_->Begin(XnaGraphics::SpriteSortMode::Deferred,\n";
            text += "                                XnaGraphics::BlendState::NonPremultiplied);\n";
            text += "            // Your drawing goes here.\n";
            text += "            spriteBatch_->End();\n";
            text += "\n";
            text += "            Game::Draw(gameTime);\n";
            text += "        }\n";
            text += "\n";
            text += "    private:\n";
            text += "        int frameLimit_ = 0;\n";
            text += "        int frames_ = 0;\n";
            text += "\n";
            text += "        std::unique_ptr<Xna::GraphicsDeviceManager> graphics_;\n";
            text += "        std::unique_ptr<XnaGraphics::SpriteBatch> spriteBatch_;\n";
            text += "    };\n";
            text += "}\n";
            text += "\n";
            text += "int main(int argc, char** argv)\n";
            text += "{\n";
            text += "    int frameLimit = 0;\n";
            text += "    for (int index = 1; index < argc; ++index)\n";
            text += "    {\n";
            text += "        const std::string argument{argv[index] != nullptr ? argv[index] : \"\"};\n";
            text += "        if (argument.rfind(\"--frames=\", 0) == 0)\n";
            text += "        {\n";
            text += "            frameLimit = std::atoi(argument.substr(9).c_str());\n";
            text += "        }\n";
            text += "        else if (argument == \"--help\")\n";
            text += "        {\n";
            text += "            std::cout << \"" + targetName + " [--frames=N]\\n\";\n";
            text += "            return 0;\n";
            text += "        }\n";
            text += "    }\n";
            text += "\n";
            text += "    try\n";
            text += "    {\n";
            text += "        " + targetName + "Game game{frameLimit};\n";
            text += "        game.Run();\n";
            text += "\n";
            text += "        // Printed rather than merely returned, so an automated smoke test can\n";
            text += "        // tell a game that ran from one that opened a window and exited.\n";
            text += "        std::cout << \"" + targetName + ": ran \" << game.framesRun() << \" frames\\n\";\n";
            text += "        return 0;\n";
            text += "    }\n";
            text += "    catch (const std::exception& error)\n";
            text += "    {\n";
            text += "        std::cerr << \"" + targetName + ": \" << error.what() << \"\\n\";\n";
            text += "        return 2;\n";
            text += "    }\n";
            text += "}\n";
            return text;
        }

        /** @brief The README a person who has never run Studio reads first. */
        std::string readmeFor(const std::string& targetName,
                              const std::string& projectName,
                              const StudioTargetProfile& profile,
                              const std::string& contentRow)
        {
            std::string text;
            text += "# " + projectName + "\n\n";
            text += "A CNA game. It was authored in CNA Studio and does not need it: nothing in\n";
            text += "this directory refers to Studio, and nothing here expects it to be installed.\n\n";
            text += "## Building\n\n";
            text += "You need CMake 3.20 or newer, a C++23 compiler, and a checkout of CNA.\n\n";
            text += "```\n";
            text += "cmake -S . -B build -DCNA_ROOT=/path/to/cna\n";
            text += "cmake --build build\n";
            text += "```\n\n";
            text += "CNA does not install a CMake package configuration, so its source checkout is\n";
            text += "what you point `CNA_ROOT` at. That is how every CNA project is built today,\n";
            text += "CNA Studio included.\n\n";
            text += "## Running\n\n";
            text += "```\n";
            text += "./build/" + targetName + "\n";
            text += "```\n\n";
            text += "`--content=DIR` points at a different content directory; `--frames=N` runs for\n";
            text += "a fixed number of frames and exits, which is what an automated test wants.\n\n";
            text += "## What is in here\n\n";
            text += "| Path | What it is |\n";
            text += "|------|------------|\n";
            text += "| `Source/Main.cpp` | Your game's entry point. Yours to edit |\n";
            text += "| `Runtime/` | The scene runtime, as project-owned source |\n";
            text += contentRow;
            text += "| `CMakeLists.txt` | The build. Yours to edit |\n\n";
            text += "## Renderer and platform\n\n";
            text += "This project was authored for the **" + studioRendererCnaIdentity(profile.renderer)
                  + "** renderer on the **" + studioPlatformCnaIdentity(profile.platform)
                  + "** platform, which is what `CMakeLists.txt` defaults to. Both are ordinary\n";
            text += "CNA configure options and either can be overridden:\n\n";
            text += "```\n";
            text += "cmake -S . -B build -DCNA_ROOT=/path/to/cna -DCNA_GRAPHICS_RENDERER=SOFTWARE\n";
            text += "```\n";
            return text;
        }

        /** @brief The note explaining why a copy of somebody else's source is sitting here. */
        std::string runtimeReadme()
        {
            std::string text;
            text += "# Runtime\n\n";
            text += "The code that reads the scene files in `../Content`. It is **project-owned\n";
            text += "source**: it is compiled as part of this game, and no library, SDK or editor\n";
            text += "has to be installed on the machine that builds it.\n\n";
            text += "It came out of CNA Studio, which is where the scene format is defined, and it\n";
            text += "is the same code Studio itself compiles -- not a reimplementation that could\n";
            text += "read the format differently.\n\n";
            text += "You can edit it. Nothing will overwrite it: re-exporting into a directory that\n";
            text += "already has these files requires asking for that explicitly. If you do edit\n";
            text += "it, keep in mind that the scene format is Studio's, so a change here that\n";
            text += "disagrees with the editor will show up as a scene that loads differently from\n";
            text += "the way it was authored.\n";
            return text;
        }

        /**
         * @brief Copies a directory tree, reporting rather than failing on individual files.
         *
         * @param from Source directory. Missing is not an error -- a project with no assets yet is
         *        a normal thing to export.
         * @param to Destination directory.
         * @param prefix Path prefix recorded in @p written, so the caller reports project-relative
         *        paths.
         * @param written Every file copied, appended.
         * @param warnings Anything that could not be copied, appended.
         */
        void copyTree(const std::filesystem::path& from,
                      const std::filesystem::path& to,
                      const std::string& prefix,
                      std::vector<std::string>& written,
                      std::vector<std::string>& warnings)
        {
            std::error_code code;
            if (!std::filesystem::is_directory(from, code)) { return; }

            for (const std::filesystem::directory_entry& entry :
                 std::filesystem::recursive_directory_iterator{from, code})
            {
                if (code) { break; }
                if (!entry.is_regular_file()) { continue; }

                const std::filesystem::path relative =
                    std::filesystem::relative(entry.path(), from, code);
                if (code)
                {
                    warnings.push_back("cannot place '" + entry.path().generic_string()
                                       + "' relative to the project: " + code.message());
                    code.clear();
                    continue;
                }

                const std::filesystem::path destination = to / relative;
                std::filesystem::create_directories(destination.parent_path(), code);
                if (code)
                {
                    warnings.push_back("cannot create '" + destination.parent_path().generic_string()
                                       + "': " + code.message());
                    code.clear();
                    continue;
                }

                std::filesystem::copy_file(entry.path(), destination,
                                           std::filesystem::copy_options::overwrite_existing, code);
                if (code)
                {
                    warnings.push_back("cannot copy '" + relative.generic_string()
                                       + "': " + code.message());
                    code.clear();
                    continue;
                }

                written.push_back(prefix + relative.generic_string());
            }
        }
    }

    StudioExportResult exportStandaloneProject(const Project& project,
                                               const StudioExportRequest& request)
    {
        StudioExportResult result;

        if (request.outputDirectory.empty())
        {
            result.errorMessage = "no output directory was given";
            return result;
        }

        const std::filesystem::path root{request.outputDirectory};
        std::error_code code;

        // Refusing to write over an existing tree is the default because export writes a whole
        // directory: a tree written over one the user picked by mistake is not something an undo
        // helps with, and the mistake is easy to make from a file dialog.
        if (std::filesystem::exists(root, code) && !std::filesystem::is_empty(root, code)
            && !request.overwrite)
        {
            result.errorMessage = "'" + root.generic_string()
                                + "' already has something in it. Export to an empty directory, or "
                                  "ask for it to be overwritten.";
            return result;
        }

        std::filesystem::create_directories(root, code);
        if (code)
        {
            result.errorMessage = "cannot create '" + root.generic_string() + "': " + code.message();
            return result;
        }

        const std::string targetName = request.targetName.empty()
                                     ? studioExportTargetName(project.getName())
                                     : studioExportTargetName(request.targetName);

        // The startup scene as the exported game will see it: relative to Content, which is what
        // ends up beside the executable. A project that named no startup scene still exports; the
        // game then reports a scene it cannot find, which is a clearer failure than an export that
        // refused for a field the author may not have filled in yet.
        std::string startupScene = project.getStartupScene();
        if (startupScene.empty())
        {
            result.warnings.push_back(
                "the project names no startup scene, so the exported game has nothing to load. "
                "Set one in the project settings and export again.");
            startupScene = project.getSceneDirectory() + "/Main.cnascene";
        }

        const auto write = [&](const std::string& relative, std::string_view contents) {
            std::string errorMessage;
            if (!writeFile(root / relative, contents, errorMessage))
            {
                result.errorMessage = errorMessage;
                return false;
            }
            result.writtenFiles.push_back(relative);
            return true;
        };

        if (!write("CMakeLists.txt",
                   cmakeListsFor(targetName, project.getActiveTargetProfile(),
                                 {ContentStaging{"Content", "Content"}}, project.getKind())))
        {
            return result;
        }
        if (!write("README.md",
                   readmeFor(targetName, project.getName(), project.getActiveTargetProfile(),
                             "| `Content/` | Scenes and assets, as authored |\n")))
        {
            return result;
        }
        // The same split the Project Hub's creation makes, and for the same reason: an
        // XNA-compatible project keeps its own game loop and has no scenes, so it gets neither a
        // scene-loading `main` nor the runtime that would read one.
        const bool isNative = project.getKind() != ProjectKind::XnaCompatible;

        if (!write("Source/Main.cpp", isNative ? mainSourceFor(targetName, startupScene)
                                               : xnaMainSourceFor(targetName)))
        {
            return result;
        }

        if (isNative)
        {
            if (!write(std::string{kStudioRuntimeDirectory} + "/README.md", runtimeReadme()))
            {
                return result;
            }
            for (const StudioRuntimeSource& source : studioRuntimeSources())
            {
                if (!write(std::string{source.pathInProject}, source.contents)) { return result; }
            }
        }

        // Content keeps the project's own layout -- Scenes next to Assets -- because the scene
        // files reference their assets by the paths the project uses. Flattening it here would
        // mean rewriting every reference, which is a migration, not an export.
        copyTree(std::filesystem::path{project.resolvePath(project.getSceneDirectory())},
                 root / "Content" / project.getSceneDirectory(),
                 "Content/" + project.getSceneDirectory() + "/",
                 result.writtenFiles, result.warnings);
        copyTree(std::filesystem::path{project.resolvePath(project.getAssetDirectory())},
                 root / "Content" / project.getAssetDirectory(),
                 "Content/" + project.getAssetDirectory() + "/",
                 result.writtenFiles, result.warnings);

        return result;
    }

    std::vector<StudioProjectFile> studioCppProjectFiles(const StudioProjectScaffold& scaffold)
    {
        const std::string targetName = studioExportTargetName(scaffold.projectName);

        // The profile the generated build file defaults to. Assembled from the scaffold rather
        // than read off a Project, because the project does not exist yet -- this is what creates
        // the directory it will be opened from.
        StudioTargetProfile profile = StudioTargetProfile::defaults();
        if (!scaffold.renderer.empty()) { profile.renderer = scaffold.renderer; }

        // The startup scene as the built game will see it: under the staged Content directory,
        // keeping the project's own layout, exactly as an export presents it. A project with no
        // startup scene still gets a buildable tree -- the game then reports a scene it cannot
        // find, which is a clearer failure than a generator that refused.
        const std::string startupScene =
            scaffold.startupScene.empty() ? scaffold.sceneDirectory + "/Main.cnascene"
                                          : scaffold.startupScene;

        // Scenes and Assets stay where the editor writes them and the build stages them beside the
        // executable. That is what makes a project created in Studio buildable *in place*, rather
        // than only after being exported: the same directory is the authoring tree and the source
        // tree, which is how every other C++ project on the machine works.
        //
        // An XNA-compatible project has no scenes at all, so it stages only its assets. Staging a
        // directory that is not there is a build that fails at the copy step, which is a confusing
        // way to be told that a project kind has no scenes.
        const bool isNative = scaffold.kind != ProjectKind::XnaCompatible;

        std::vector<ContentStaging> staging;
        if (isNative)
        {
            staging.push_back({scaffold.sceneDirectory, "Content/" + scaffold.sceneDirectory});
        }
        staging.push_back({scaffold.assetDirectory, "Content/" + scaffold.assetDirectory});

        std::string contentRows;
        if (isNative) { contentRows += "| `" + scaffold.sceneDirectory + "/` | Your scenes |\n"; }
        contentRows += "| `" + scaffold.assetDirectory + "/` | Your assets |\n";

        std::vector<StudioProjectFile> files;
        files.push_back({"CMakeLists.txt",
                         cmakeListsFor(targetName, profile, staging, scaffold.kind)});
        files.push_back({"README.md",
                         readmeFor(targetName, scaffold.projectName, profile, contentRows)});
        files.push_back({"Source/Main.cpp",
                         isNative ? mainSourceFor(targetName, startupScene)
                                  : xnaMainSourceFor(targetName)});

        // The scene runtime travels with a project that has scenes, and only with one. A
        // hand-written game compiling a loader for a format it never reads would be carrying a
        // file nobody can explain.
        if (isNative)
        {
            files.push_back({std::string{kStudioRuntimeDirectory} + "/README.md", runtimeReadme()});
            for (const StudioRuntimeSource& source : studioRuntimeSources())
            {
                files.push_back({std::string{source.pathInProject}, std::string{source.contents}});
            }
        }
        return files;
    }
}
