# SPDX-License-Identifier: MS-PL
#
# Turns a binary file into a C++ translation unit defining a byte array and its length.
#
# Run in script mode from a custom command:
#
#   cmake -DINPUT=<file> -DOUTPUT=<file.cpp> -DSYMBOL=<name> -DNAMESPACE=<ns> -P EmbedBinary.cmake
#
# The generated file is a build artefact, never committed. The binary is the source of truth, and a
# committed copy of its bytes in another encoding would be a second one: free to drift from the
# original, and impossible to review.

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
    message(FATAL_ERROR "EmbedBinary.cmake needs INPUT, OUTPUT and SYMBOL")
endif()

if(NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "EmbedBinary.cmake: '${INPUT}' does not exist")
endif()

file(READ "${INPUT}" _hex HEX)
string(LENGTH "${_hex}" _hexLength)
math(EXPR _byteCount "${_hexLength} / 2")

if(_byteCount EQUAL 0)
    message(FATAL_ERROR "EmbedBinary.cmake: '${INPUT}' is empty")
endif()

# One regex pass over the whole file. Emitting a newline every 32 bytes keeps the generated file
# openable in an editor, which matters the one time somebody needs to look at it.
string(REGEX REPLACE "(................................................................)" "\\1\n"
       _wrapped "${_hex}")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_wrapped}")

set(_namespaceOpen "")
set(_namespaceClose "")
if(DEFINED NAMESPACE)
    set(_namespaceOpen "namespace ${NAMESPACE} {")
    set(_namespaceClose "} // namespace ${NAMESPACE}")
endif()

file(WRITE "${OUTPUT}"
"// SPDX-License-Identifier: MS-PL
// Generated by cmake/EmbedBinary.cmake from ${INPUT}. Do not edit; do not commit.
${_namespaceOpen}
extern const unsigned char ${SYMBOL}[];
extern const unsigned long ${SYMBOL}Size;
const unsigned char ${SYMBOL}[] = {
${_bytes}
};
const unsigned long ${SYMBOL}Size = ${_byteCount}UL;
${_namespaceClose}
")
